### ISSUE TITLE
Sorry, What is the point of this caddy-cloudflare-ip?

### ISSUE THREAD

**Issue by houmie** [WeidiDeng/caddy-cloudflare-ip#2]
Hello,

Apologies, I have been researching for many hours, but haven't been able to find more information about this. 

```
"trusted_proxies": {
  "source": "cloudflare",
  "interval": "12h",
  "timeout": "15s"
},
```

I understand under Caddy I can use this section above to fetch a list of trusted proxies.  But why do I need `caddy-cloudflare-ip` when I have already enabled CloudFlare's proxy?

<img width="124" alt="Screenshot 2023-06-05 at 18 03 01" src="https://github.com/WeidiDeng/caddy-cloudflare-ip/assets/1832933/eb1fbb22-1cfc-4230-b3c6-a37ad5cad498">

I'm planning to use Caddy with Xray to create the following VPN protocols that utilise Cloudflare CDN.
```
VLESS+gRPC+TLS
VLESS+WS+TLS
Trojan+gRPC+TLS
VMess+WS+TLS
```

Many Thanks

**Comment by francislavoie** [comment]
Your server is still reachable by using its direct IP address. Nothing prevents clients from bypassing Cloudflare and hitting your server directly. So you should only mark IP addresses controlled by Cloudflare as trusted, so that the parsed client IP is only ever the one Cloudflare saw at their end.

**Comment by WeidiDeng** [comment]
As francis said, it's mainly used to pass reliable `X-Forwarded-For` header to your xray server so forged `X-Forwarded-For` is mostly filtered. If you don't care about from where clients are connecting to your server, you can safely ignore this.

**Comment by houmie** [comment]
Awesome. Thank you both for explaining this to me. 

Have a great day.
