### ISSUE TITLE
support remote_ip filtering

### ISSUE THREAD

**Issue by lanrat** [WeidiDeng/caddy-cloudflare-ip#3]
This module is great.

Would it be possible to also add support for Caddy's [remote_ip](https://caddyserver.com/docs/caddyfile/matchers#remote-ip) matcher as well?

It would be great if I would use the same up to date list of cloudflare proxy IPs to also reject requests not originating from cloudflare as well.

Thanks.

**Comment by francislavoie** [comment]
You can use https://github.com/tuzzmaniandevil/caddy-dynamic-clientip which gives you a matcher that can get IPs from an IP source plugin like this one.

**Comment by lanrat** [comment]
[caddy-dynamic-clientip](https://github.com/tuzzmaniandevil/caddy-dynamic-clientip) seems like a great solution!

I'm having some trouble getting it working. When I specify the IP ranges manually it works, but if I use `dynamic_client_ip`, nothing is matched.

This works:
```
@not-cf not remote_ip 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32
abort @not-cf
```

This does not work:
```
@not-cf not dynamic_client_ip cloudflare
abort @not-cf
```

Is my syntax here correct?

**Comment by francislavoie** [comment]
Seems right. In what way does it not work? You should probably ask for help on that plugin's github issues otherwise, I don't use it and I can't provide support for it.

**Comment by lanrat** [comment]
Oh, I think I know the issue.

`dynamic_client_ip` matches `client_ip`, which is the end user's IP. For a reverse proxy like Cloudflare, you need to match on `remote_ip` which `dynamic_client_ip` does not do.

`dynamic_client_ip` is working as intended. But does not help with my request here.

**Comment by francislavoie** [comment]
Ah, right. Well you can probably fork it and adjust it to do specifically that. It's a super simple plugin.

**Comment by lanrat** [comment]
Done! https://github.com/lanrat/caddy-dynamic-remoteip

```
@not-cf not dynamic_remote_ip cloudflare
abort @not-cf
```

**Comment by francislavoie** [comment]
Nice! Consider registering it at https://caddyserver.com/download by making an account https://caddyserver.com/account and claiming the plugin :+1:

**Comment by lanrat** [comment]
https://caddyserver.com/docs/modules/http.matchers.dynamic_remote_ip

:smile:
