### ISSUE TITLE
invalid IP address: 'cloudflare': ParseAddr("cloudflare"): unable to parse IP

### ISSUE THREAD

**Issue by cellulosa** [WeidiDeng/caddy-cloudflare-ip#7]
heya, I'm building this with:

```Dockerfile
FROM caddy:builder AS builder

RUN xcaddy build \
	--with github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

But am getting this error when launching:

```shell
invalid IP address: 'cloudflare': ParseAddr("cloudflare"): unable to parse IP
```

Thsi is my Caddifile

```Caddyfile
{
	servers {
		trusted_proxies static 192.168.0.10 cloudflare {
			interval 12h
			timeout 15s
		}
	}
}
```

**Comment by mrrfv** [comment]
Try putting `cloudflare` before `static` (or even repeating the `trusted_proxies` option for both modules if that doesn't work). `cloudflare` in your current Caddyfile is parsed as an IP address, according to the Caddy documentation: https://caddyserver.com/docs/caddyfile/options#trusted-proxies

**Comment by francislavoie** [comment]
To merge two lists of IPs (cloudflare + static), you should use https://github.com/fvbommel/caddy-combine-ip-ranges which can take more than one IP source plugin.

**Comment by cellulosa** [comment]
lovely, thank you!

**Comment by cellulosa** [comment]
lovely, thank you!
